services:
  app:
    image: ghcr.io/ismola/jw-hitster:main
    container_name: jw-hitster-app
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: ghcr.io/ismola/jw-hitster-nginx:main
    container_name: jw-hitster-nginx
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
